#!/bin/sh


cat $pathToRepoRoot/src/emmet.js | sed 1d > $pathToRepoRoot/emmet.full.js
echo -e "\n" >> $pathToRepoRoot/emmet.full.js
cat $pathToRepoRoot/src/data.js | sed 1d  >> $pathToRepoRoot/emmet.full.js
echo -e "\n" >> $pathToRepoRoot/emmet.full.js
cat $pathToRepoRoot/src/fsm.js  | sed 1d  >> $pathToRepoRoot/emmet.full.js
echo -e "\n" >> $pathToRepoRoot/emmet.full.js
cat $pathToRepoRoot/src/node.js | sed 1d  >> $pathToRepoRoot/emmet.full.js
echo -e "\n" >> $pathToRepoRoot/emmet.full.js
cat $pathToRepoRoot/src/pn.js   | sed 1d  >> $pathToRepoRoot/emmet.full.js



java -jar /usr/share/yui-compressor/yui-compressor.jar $pathToRepoRoot/emmet.full.js -o $pathToRepoRoot/emmet.min.js

