#!/bin/bash

cat $pathToGitRoot/src/emmet.js | sed 's/"use strict;"//'   > $pathToGitRoot/emmet.full.js
cat $pathToGitRoot/src/data.js  | sed 's/"use strict;"//'  >> $pathToGitRoot/emmet.full.js
cat $pathToGitRoot/src/fsm.js   | sed 's/"use strict;"//'  >> $pathToGitRoot/emmet.full.js
cat $pathToGitRoot/src/node.js  | sed 's/"use strict;"//'  >> $pathToGitRoot/emmet.full.js
cat $pathToGitRoot/src/pn.js    | sed 's/"use strict;"//'  >> $pathToGitRoot/emmet.full.js


java -jar /usr/share/yui-compressor/yui-compressor.jar $pathToGitRoot/emmet.full.js -o $pathToGitRoot/emmet.min.js


echo 'Updating emmet.min.js' > $pathToGitRoot/post-commit.lock

git commit -m 'update min.js' $pathToGitRoot/emmet.min.js

rm $pathToGitRoot/post-commit.lock

