"use strinct;"
function FSM(){
     var map = {
        "operator" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "operator",
            ")" : "operator",
            "a" : "tag",
            "#" : "id",
            "." : "class_name",
            "[" : "attr",
            "]" : "error",
            "{" : "text_node",
            "}" : "error",
            "*" : "multi",
            "`" : "html_var",
            "%" : "html_func",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },
        "tag" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "same",
            "#" : "id",
            "." : "class_name",
            "[" : "attr",
            "]" : "error",
            "{" : "text",
            "}" : "error",
            "*" : "multi",
            "`" : "tag_var",
            "%" : "tag_func",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },
        "tag_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "tag",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "tag_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "tag_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "tag",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "tag_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "tag_func",
            "a" : "tag_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "tag_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "tag_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "tag_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "tag_args"
        },
        "tag_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "tag_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"                                                            
        },
        "id" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "same",
            "#" : "error",
            "." : "class_name",
            "[" : "attr",
            "]" : "error",
            "{" : "text",
            "}" : "error",
            "*" : "multi",
            "`" : "id_var",
            "%" : "id_func",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },
        "id_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "id",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "id_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "id_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "id",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "id_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "id_func",
            "a" : "id_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "id_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "id_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "id_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "id_args"
        },
        "id_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "id_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "class_name" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "same",
            "#" : "error",
            "." : "class_name",
            "[" : "attr",
            "]" : "error",
            "{" : "text",
            "}" : "error",
            "*" : "multi",
            "`" : "class_name_var",
            "%" : "class_name_func",
            " " : "same",
            ""  : "end",
            "," : "error"
        },
        "class_name_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "class_name",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "class_name_func" : {
            "+": "error",
            ">": "error",
            "^": "error",
            "(": "class_name_args",
            ")": "error",
            "a": "same",
            "#": "error",
            ".": "error",
            "[": "error",
            "]": "error",
            "{": "error",
            "}": "error",
            "*": "error",
            "`": "error",
            "%": "class_name",
            " ": "skip",
            "": "error",
            ",": "error"
        },
        "class_name_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "class_name_func",
            "a" : "class_name_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "class_name_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "class_name_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "class_name_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "class_name_args"
        },
        "class_name_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "class_name_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },

        "attr" : {
            "+" : "same",
            ">" : "same",
            "^" : "same",
            "(" : "same",
            ")" : "same",
            "a" : "same",
            "#" : "same",
            "." : "same",
            "[" : "error",
            "]" : "after_attr",
            "{" : "same",
            "}" : "same",
            "*" : "same",
            "`" : "attr_var",
            "%" : "attr_func",
            " " : "same",
            ""  : "error",
            "," : "same"
        },
        "attr_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "attr",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "attr_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "attr_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "attr",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "attr_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "attr_func",
            "a" : "attr_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "attr_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "attr_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "attr_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "attr_args"
        },
        "attr_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "attr_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "after_attr" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "error",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "text",
            "}" : "error",
            "*" : "multi",
            "`" : "error",
            "%" : "error",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },
        "text" : {
            "+" : "same",
            ">" : "same",
            "^" : "same",
            "(" : "same",
            ")" : "same",
            "a" : "same",
            "#" : "same",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "error",
            "}" : "after_text",
            "*" : "same",
            "`" : "text_var",
            "%" : "text_func",
            " " : "same",
            ""  : "error",
            "," : "same"
        },
        "text_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "text",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "text_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "text_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "text",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "text_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "text_func",
            "a" : "text_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "text_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "text_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "text_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "text_args"
        },
        "text_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "text_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "after_text" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "error",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "multi",
            "`" : "error",
            "%" : "error",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },
        "text_node" : {
            "+" : "same",
            ">" : "same",
            "^" : "same",
            "(" : "same",
            ")" : "same",
            "a" : "same",
            "#" : "same",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "error",
            "}" : "after_text_node",
            "*" : "same",
            "`" : "text_node_var",
            "%" : "text_node_func",
            " " : "same",
            ""  : "error",
            "," : "same"
        },
        "text_node_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "text_node",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "text_node_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "text_node_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "text_node",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "text_node_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "text_node_func",
            "a" : "text_node_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "text_node_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "text_node_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "text_node_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "text_node_args"
        },
        "text_node_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "text_node_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "after_text_node" : {
            "+" : "operator",
            ">" : "error",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "error",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "multi",
            "`" : "error",
            "%" : "error",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },

        "multi" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "multi_var",
            "%" : "multi_func",
            " " : "same",
            ""  : "end",
            "," : "error"
        },
        "multi_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "multi",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "multi_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "multi_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "multi",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "multi_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "multi_func",
            "a" : "multi_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "multi_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "multi_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "multi_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "multi_args"
        },
        "multi_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "multi_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "error" : {},
        "end" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "error",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "html" : {
            "+" : "operator",
            ">" : "operator",
            "^" : "operator",
            "(" : "error",
            ")" : "operator",
            "a" : "error",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "multi",
            "`" : "error",
            "%" : "error",
            " " : "skip",
            ""  : "end",
            "," : "error"
        },
        "html_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "html",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        },
        "html_func" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "html_args",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "html",
            " " : "skip",
            ""  : "error",
            "," : "error"
        },
        "html_args" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "html_func",
            "a" : "html_arg_txt",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "html_arg_var",
            "%" : "error",
            " " : "skip",
            ""  : "error",
            "," : "skip"
        },
        "html_arg_txt" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "html_func",
            "a" : "same",
            "#" : "error",
            "." : "error",
            "[" : "error",
            "]" : "error",
            "{" : "error",
            "}" : "error",
            "*" : "error",
            "`" : "error",
            "%" : "error",
            " " : "same",
            ""  : "error",
            "," : "html_args"
        },
        "html_arg_var" : {
            "+" : "error",
            ">" : "error",
            "^" : "error",
            "(" : "error",
            ")" : "error",
            "a" : "same",
            "#" : "error",
            "." : "same",
            "[" : "same",
            "]" : "same",
            "{" : "same",
            "}" : "same",
            "*" : "error",
            "`" : "html_args",
            "%" : "error",
            " " : "error",
            ""  : "error",
            "," : "error"
        }


    };
    this.prev_state = this.state =  "tag";
    this.is_state_changed = true;

    var alphabet = ["+", ">", "^", "(", ")", "a", "#", ".", "[", "]", "{", "}", "*", "`", "%", " ", "", ","];

    this.setState = function(symbol){
        if("error" === this.state){
            throw new Error("Finite State Machine Error.");
        }
        var key = '';
        if(-1 === alphabet.indexOf(symbol)){
            key = "a";
        } else {
            key = symbol;
        }

        var state = map && map[this.state] && map[this.state][key];

        this.is_state_changed = false;

        switch(state){
            case "same":
                break;
            case "skip":
                break;
            default:
                this.prev_state       = this.state;
                this.is_state_changed = true;
                this.state            = state;
                break;
        }

        return true;
    }

};

